[package]
name = "cat_web"
version = "0.1.0"
authors = ["Clomance<hisoskar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
opt-level = 3

[target.'cfg(target_os="linux")'.dependencies.signal-hook]
version = "0.3.14"

[dependencies]
urlencoding = "2.1.0"